CREATE TABLE IF NOT EXISTS people
(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
fio VARCHAR (255) NOT NULL,
year_birthday INT NOT NULL,
UNIQUE(fio)
);

CREATE TABLE IF NOT EXISTS books
(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
people_id INT,
name VARCHAR (255) NOT NULL,
author VARCHAR (255) NOT NULL,
years INT NOT NULL,
FOREIGN KEY(people_id) REFERENCES people(id) ON DELETE SET NULL
);

